name: 03 - workflow

on:
    push:

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run:  |
                echo "This job is running on the following OS:"
                echo $RUNNER_OS
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run:  |
                echo "This job is running on the following OS:"
                echo $RUNNER_OS