name: 04 - workflow

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04/react-app        
        steps:
            # Check out code
            - name: Check out code
              uses: actions/checkout@v4
            
            # Set up Node.js
            - name: Setup Note
              uses: actions/setup-node@v3
              with:
                node-version: '23.x'
            
            # Install dependencies
            - name: Install dependencies
              run: npm ci
            
            # Execute tests
            - name: Run unit tests
              run: npm run test