name: 05-1 - workflow

on:
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenever a pull request (PR) is opened or synchronized AND base branch is main"