name: 05-2 - workflow

on:
    pull_request:
        types:
            - closed
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenever a pull request (PR) is closed AND base branch is main"